config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :aadresses, only: [:create, :destroy]
  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get "/404", :to => "static_pages#home"
  get "/422", :to => "static_pages#home"
  get "/500", :to => "static_pages#home"
  get "/505", :to => "static_pages#home"

end

app/models/aadress.rb
class Aadress < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :maja, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :aadresses, dependent: :destroy
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
    validates :password, length: { minimum: 6 }
	accepts_nested_attributes_for :aadresses, allow_destroy: true
	def User.new_remember_token
      SecureRandom.urlsafe_base64
    end
  
    def User.digest(token)
      Digest::SHA1.hexdigest(token.to_s)
    end

    private

      def create_remember_token
        self.remember_token = User.digest(User.new_remember_token)
      end
end

app/controllers/aadresses_controller.rb
class AadressesController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
	@saved_user = User.find_by(email: cookies[:user_token])
    @aadress = saved_user.aadresses.build(aadress_params)
	#@def = aadress_params[:maja] + ", " + aadress_params[:linn]
	#@aadress2 = current_user.update_attribute(:aadress, @def)
    if @aadress.save
      flash[:success] = "Aadress lisatud!"
      redirect_to saved_user
    else
      render 'static_pages/home'
    end
  end

  def destroy
  
    @aadress.destroy
    redirect_to saved_user
  end

  private

    def aadress_params
      params.require(:aadress).permit(:maja, :linn)
    end
	
	def aadress2_params
      params.require(:aadress).permit(:maja)
    end
	
	def correct_user
	@saved_user = User.find_by(email: cookies[:user_token])
      @aadress = saved_user.aadresses.find_by(id: params[:id])
      redirect_to root_url if @aadress.nil?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @aadress = current_user.aadresses.build if signed_in?
  end

  def help
  end
  
  def about
  end
    
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
	save_user(@user)
	unless @user.aadresses.first.nil?
	  @def = @user.aadresses.first.maja + ", " + @user.aadresses.first.linn
	  @user.update_attribute(:aadress, @def)
	end
	if @user.aadresses.first.nil?
	  @user.update_attribute(:aadress, '')
	end
	@aadresses = @user.aadresses.paginate(page: params[:page])
	@aadress = @user.aadresses.build if signed_in?
	
  end
  
  def new
	@user = User.new
  end
  
  def index
    @search = User.search(params[:q])
    @users = @search.result.order('updated_at DESC')
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
	  sign_in @user
	  flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end	
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :aadress, :password,
                                   :password_confirmation)
    end
	
	# Before filters


    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) || current_user.admin?
    end
	def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Klientide haldusprogramm"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end
  def signed_in?
    !current_user.nil?
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def save_user(user)
	cookies.permanent[:user_token] = user.email

  end
  
  def saved_user
	user_token = User.digest(cookies[:user_token])
	@saved_user ||= User.find_by(email: user_token)
  end
  
  def current_user?(user)
    user == current_user
  end
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Palun logi sisse"
    end
  end
  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/aadresses/_aadress.html.erb
<li>
  <span class="content"><%= aadress.maja %>, <%= aadress.linn %> <% if current_user?(aadress.user) || current_user.admin? %> | 
    <%= link_to "Kustuta", aadress, method: :delete,
                                     data: { confirm: "Oled kindel?" } %> |
  <% end %></span>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.unlocktallinn.ee">UnlockTallinn</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "klientide halduse programm", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
		    <li><%= link_to "Avaleht", root_path %></li>
            <li><%= link_to "Kasutajad", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= @current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Aadressid", current_user %></li>
                <li><%= link_to "Seaded", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Logi välja", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Logi sisse", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_aadress_form.html.erb
<%= form_for(@aadress) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :maja, placeholder: "Tänav-maja number" %>
	<%= f.text_field :linn, placeholder: "Linn" %>
	
  </div>
  <%= f.submit "Lisa aadress", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      Vorm sisaldab <%= object.errors.count %> viga.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "Profiil", current_user %>
</span>
<span>
  Kasutajal on <%= current_user.aadresses.count %> aaressi
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact leht</h1>
<p>
  This is the contact page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/help.html.erb
<%= search_form_for @search, url: help_path, method: :post do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>
  <% end %>
  <p><%= link_to_add_fields "Add Conditions", f, :condition %></p>
  <div class="field">
    Sort:
    <%= f.sort_fields do |s| %>
      <%= s.sort_select %>
    <% end %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

<table id="kliendid">
  <tr>
    <th><%= sort_link @search, :name, "Kliendi nimi" %></th>
    <th><%= sort_link @search, :email, "email" %></th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td><%= link_to(user.name, user) %></td>
    <td><%= user.email %></td>
  </tr>
<% end %>
</table>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Klientide halduse programm</h1>

  <h2>
    Tegemist on õppeaine IDU0200-Veebipõhiste rakenduste arhitektuur, disain ja tehnoloogia tarbeks loodud klientide halduse programmiga
  </h2>

  <%= link_to "Loo konto", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/_user.html.erb
<tr>
<td>
  <%= link_to user.name, user %>
</td>
<td>
  <%= user.email %>
</td>
<td>
  <%= user.aadress %>
</td>

  <% if current_user.admin? && !current_user?(user) %>
  <td>
    <%= link_to "Kustuta", user, method: :delete,
                                  data: { confirm: "Oled kindel?" } %>
  </td>
  <% end %>
  
  <% if current_user.admin? && current_user?(user) %>
  <td>
    -
  </td>
  <% end %>

  <% if current_user.admin? %>
  <td>
    <%= user.admin %>
  </td>
  <td>
    <%= link_to "Muuda", edit_user_path(user.id) %>
  </td>
  <% end %>

</tr>

app/views/users/edit.html.erb
<% provide(:title, "Uuenda andmeid") %>
<h1>Uuenda andmeid</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "Nimi" %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>
	  
	  <% f.fields_for :aadresses do |builder| %>
		<p>
			<%= builder.label :maja, "Maja" %>
			<%= builder.text_field :maja %>
		</p>
		<p>
			<%= builder.label :linn, "Linn" %>
			<%= builder.text_field :linn %>
		</p>
	  <% end %>
	  
      <%= f.label :password, "Parool" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Parooli kinnitus" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Salvesta muudatused", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">muuda</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Kliendid') %>
<h1>Kõik kliendid</h1>

<%= search_form_for @search do |f| %>
  <div class="field">
    <%= f.label :name_cont, "Nimi sisaldab" %>
    <%= f.text_field :name_cont %>
  </div>
    <div class="field">
    <%= f.label :aadress_cont, "Aadress sisaldab" %>
    <%= f.text_field :aadress_cont %>
  </div>
  <div class="actions"><%= f.submit "Otsi", class: "btn btn-primary" %></div>
<% end %>

<table class="table table-striped">
  <tr>
    <th><%= sort_link @search, :name, "Nimi" %></th>
    <th><%= sort_link @search, :email, "email" %></th>
	<th><%= sort_link @search, :aadress, "Aadress" %></th>
	<% if current_user.admin? %>
      <th>Kustuta</th>
	  <th><%= sort_link @search, :admin, "Admin?" %></th></th>
	<th>Muuda</th>
	<% end %>
  </tr>
<%= render @users %>
</table>

app/views/users/index.html_sunspot.erb
<% provide(:title, 'Kliendid') %>
<h1>Kõik kliendid</h1>

<%= form_tag users_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<div>
  <%= render @users %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Loo konto') %>
<h1>Loo konto</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Nimi" %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>


      <%= f.label :password, "Parool" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Parooli kinnitus" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Loo konto", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js">
</script>
<script>
$(document).ready(function(){
  $("section1").hide();
  $("#show").click(function(){
    $("section1").show();
  });
});
</script>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
	  <%= @user.email %>
    </section>
	<% if current_user.admin? %>
      <%= link_to "Muuda andmeid", edit_user_path(@user.id) %>
    <% end %>
  </aside>
  <% if current_user?(@user) || current_user.admin? %>
    <div class="row">
      <aside class="span4">
        <section>
          <%= render 'shared/aadress_form' %>
        </section>
      </aside>
    </div>
  <% end %>
  <div class="span8">
    <% if @user.aadresses.any? %>
	  <h3>Aadresse: <%= @user.aadresses.count %></h3>
	  <button id="show", class='btn btn-info'>Näita aadresse</button>
      <section1>
	  <ol class="aadresses">
        <%= render @aadresses %>
      </ol>
	  <%= will_paginate @aadresses %>
	  	  </section1>
    <% end %>
  </div>
</div>